version: '3'

services:
  postgres:
    image: "postgres:${POSTGRES_VER}"
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pleroma

  web:
    build:
      context: ./
      args:
        PLEROMA_VER: ${PLEROMA_VER}
    image: pleroma:${PLEROMA_VER}
    restart: always
    volumes:
      - pleroma-uploads:/pleroma/uploads
      - ./config/prod.secret.exs:/pleroma/config/prod.secret.exs
      - ./config/keys.secret.exs:/pleroma/config/keys.secret.exs
      - ./config/emoji:/pleroma/priv/static/emoji/custom
      #- ./config/instance:/pleroma/priv/static/instance
      #- ./config/terms-of-service.html:/pleroma/priv/static/static/terms-of-service.html
    depends_on:
      - postgres
    networks:
      - pleroma
      - voyager_link

volumes:
  postgres-data:
    driver: local
  pleroma-uploads:
    driver: local

networks:
  pleroma:
    driver: bridge
  voyager_link:
    external: true
