version: '3'

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: pleroma
      POSTGRES_PASSWORD: pleroma
      POSTGRES_DB: pleroma
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pleroma

  web:
    build:
      context: ./
      args:
        PLEROMA_VER: ${PLEROMA_VER}
    image: pleroma:${PLEROMA_VER}
    restart: always
    volumes:
      - pleroma-uploads:/pleroma/uploads
      - ./config/prod.secret.exs:/pleroma/config/prod.secret.exs
      - ./config/keys.secret.exs:/pleroma/config/keys.secret.exs
      - ./config/emoji:/pleroma/priv/static/emoji/custom
      #- ./config/instance:/pleroma/priv/static/instance
      #- ./config/terms-of-service.html:/pleroma/priv/static/static/terms-of-service.html
    depends_on:
      - postgres
    networks:
      - pleroma
      - voyager_link

volumes:
  postgres-data:
    driver: local
  pleroma-uploads:
    driver: local

networks:
  pleroma:
    driver: bridge
  voyager_link:
    external: true
