version: '3'

services:
  postgres:
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_USER: pleroma
      POSTGRES_PASSWORD: pleroma
      POSTGRES_DB: pleroma
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pleroma

  web:
    build: .
    image: pleroma
    restart: always
    volumes:
      - pleroma-uploads:/pleroma/uploads
    depends_on:
      - postgres
    networks:
      - pleroma

volumes:
  postgres-data:
    driver: local
  pleroma-uploads:
    driver: local

networks:
  pleroma:
    driver: bridge
